# Generated by Django 4.2.3 on 2023-08-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_order_address_order_phone_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
    ]
