# Generated by Django 4.2.3 on 2023-08-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
